[project]
authors = [{name = "cai zikun"}]
dependencies = []
name = "lerobot_policy_trans"
requires-python = ">= 3.10"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

